const { ChatOpenAI } = require("@langchain/openai");
const { PromptTemplate } = require("@langchain/core/prompts");
const { StructuredOutputParser } = require("langchain/output_parsers");
const { z } = require("zod");

class ValuationAnalysisAgent {
    /**
     * Final stage reasoning agent. Synthesizes metrics and sector data
     * to arrive at a high-level investment valuation conclusion.
     */
    constructor() {
        // Temperature 0.2 allows for slight analytical nuance while remaining factual
        this.llm = new ChatOpenAI({ modelName: "gpt-4o", temperature: 0.2 });

        this.parser = StructuredOutputParser.fromZodSchema(z.object({
            valuation: z.string().describe("Valuation verdict: MUST BE 'Undervalued', 'Overvalued', or 'Fairly valued'."),
            reasoning: z.string().describe("Comprehensive financial explanation behind the verdict based on metrics (e.g. ROE) relative to standard expectations for the sector."),
            confidence_score: z.number().describe("Agent's analytical confidence in this analysis from 0.0 to 1.0 (e.g. 0.91)."),
            references: z.array(z.string()).describe("List combining all source documents and pages supporting this analysis.")
        }));
    }

    /**
     * Final agent in the pipeline.
     * @param {string} companyName 
     * @param {Object} sectorData - Generated by SectorClassificationAgent
     * @param {Object} metricsData - Generated by MetricsExtractionAgent
     * @returns {Promise<Object>} JSON containing the final verdict seamlessly formatted.
     */
    async analyzeValuation(companyName, sectorData, metricsData) {
        console.log(`Valuation Analysis Agent: Synthesizing metrics and sector for fair value verdict of ${companyName}...`);

        const formatInstructions = this.parser.getFormatInstructions();

        const promptString = `You are a senior equity valuation analyst for FinSathi AI specializing in the Nepal Stock Exchange.
Determine the valuation of {company_name} which operates in the {sector} sector.

Here are the extracted financial metrics previously sourced:
- ROE: {roe}
- P/E Ratio: {pe}
- P/B Ratio: {pb}
- Revenue Growth: {growth}

Original Sources from previous agents:
Metrics Sourced From: {metrics_refs}
Sector Sourced From: {sector_refs}

Evaluate these ratios relative to general emerging market / NEPSE benchmarks.
Determine if the company is Undervalued, Overvalued, or Fairly valued. 
Provide a confidence score between 0.0 and 1.0 based on how complete and reliable the provided metrics are. 
If critical metrics (like PE or PB) are 'N/A', significantly lower your confidence_score.
Combine and list the references explicitly using your inputs.

{format_instructions}`;

        const promptTemplate = new PromptTemplate({
            template: promptString,
            inputVariables: ["company_name", "sector", "roe", "pe", "pb", "growth", "metrics_refs", "sector_refs"],
            partialVariables: { format_instructions: formatInstructions }
        });

        const prompt = await promptTemplate.format({
            company_name: companyName,
            sector: sectorData.sector,
            roe: metricsData.ROE,
            pe: metricsData.PE_Ratio,
            pb: metricsData.PB_Ratio,
            growth: metricsData.Revenue_Growth,
            metrics_refs: metricsData.references.join(" | "),
            sector_refs: sectorData.references.join(" | ")
        });

        const response = await this.llm.invoke(prompt);
        return await this.parser.parse(response.content);
    }
}

module.exports = ValuationAnalysisAgent;
